stages:
  - test

sudo: required
cache: bundler
language: ruby

services:
  - docker

before_install:
  - bundle install

# Make sure the instances listed below match up with
# the `platforms` defined in `kitchen.yml`
env:
  matrix:
    - INSTANCE: default-debian-9-2019-2-py3
    - INSTANCE: default-ubuntu-1804-2019-2-py3
    - INSTANCE: default-centos-7-2019-2-py2
    - INSTANCE: default-fedora-29-2019-2-py2
    - INSTANCE: default-opensuse-423-2018-3-py2
    - INSTANCE: default-debian-8-2018-3-py2
    - INSTANCE: default-ubuntu-1604-2018-3-py2
    - INSTANCE: default-fedora-28-2018-3-py2
    - INSTANCE: default-debian-8-2017-7-py2
    - INSTANCE: default-ubuntu-1604-2017-7-py2

script:
  - bundle exec kitchen verify ${INSTANCE}
